apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-app
spec:
  template:
    spec:
      containers:
        - image: europe-west1-docker.pkg.dev/startupsdna-tools/test/app:3033567
