name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Docker Auth
        run: ./deployment/docker/auth.sh -e dev
      - name: Run app deployment script
        run: ./deployment/deploy.app.sh -e dev
